"""baseline schema

Revision ID: 6a05e3351275
Revises: 
Create Date: 2026-08-31 14:48:03.920430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a05e3351275'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'OPEN', 'CLOSED', 'LISTED', 'WITHDRAWN', name='ipostatus'), nullable=False),
    sa.Column('ipo_type', sa.Enum('MAINBOARD', 'SME', name='ipotype'), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('allotment_date', sa.DateTime(), nullable=True),
    sa.Column('listing_date', sa.DateTime(), nullable=True),
    sa.Column('price_band_lower', sa.Float(), nullable=True),
    sa.Column('price_band_upper', sa.Float(), nullable=True),
    sa.Column('issue_price', sa.Float(), nullable=True),
    sa.Column('listing_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('return_1d', sa.Float(), nullable=True),
    sa.Column('return_1w', sa.Float(), nullable=True),
    sa.Column('return_1m', sa.Float(), nullable=True),
    sa.Column('issue_size_rs_cr', sa.Float(), nullable=True),
    sa.Column('shares_offered', sa.Integer(), nullable=True),
    sa.Column('fresh_issue_size', sa.Float(), nullable=True),
    sa.Column('offer_for_sale', sa.Float(), nullable=True),
    sa.Column('qib_subscription', sa.Float(), nullable=True),
    sa.Column('nii_subscription', sa.Float(), nullable=True),
    sa.Column('retail_subscription', sa.Float(), nullable=True),
    sa.Column('total_subscription', sa.Float(), nullable=True),
    sa.Column('gmp_amount', sa.Float(), nullable=True),
    sa.Column('gmp_percentage', sa.Float(), nullable=True),
    sa.Column('estimated_listing_price', sa.Float(), nullable=True),
    sa.Column('industry_sector', sa.String(length=100), nullable=True),
    sa.Column('lead_managers', sa.Text(), nullable=True),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('market_cap_cr', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('roce', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('profit_growth', sa.Float(), nullable=True),
    sa.Column('face_value', sa.Float(), nullable=True),
    sa.Column('revenue_cr', sa.Float(), nullable=True),
    sa.Column('profit_cr', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_category', sa.String(length=20), nullable=True),
    sa.Column('ml_processed', sa.Boolean(), nullable=True),
    sa.Column('ml_processed_at', sa.DateTime(), nullable=True),
    sa.Column('prospectus_url', sa.String(length=500), nullable=True),
    sa.Column('prospectus_file_id', sa.String(length=255), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('min_investment', sa.Float(), nullable=True),
    sa.Column('detail_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('news_and_announcements', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipos_close_date'), 'ipos', ['close_date'], unique=False)
    op.create_index(op.f('ix_ipos_company_name'), 'ipos', ['company_name'], unique=False)
    op.create_index(op.f('ix_ipos_id'), 'ipos', ['id'], unique=False)
    op.create_index(op.f('ix_ipos_industry_sector'), 'ipos', ['industry_sector'], unique=False)
    op.create_index(op.f('ix_ipos_listing_date'), 'ipos', ['listing_date'], unique=False)
    op.create_index(op.f('ix_ipos_ml_processed'), 'ipos', ['ml_processed'], unique=False)
    op.create_index(op.f('ix_ipos_open_date'), 'ipos', ['open_date'], unique=False)
    op.create_index(op.f('ix_ipos_risk_score'), 'ipos', ['risk_score'], unique=False)
    op.create_index(op.f('ix_ipos_status'), 'ipos', ['status'], unique=False)
    op.create_index(op.f('ix_ipos_symbol'), 'ipos', ['symbol'], unique=True)
    op.create_index(op.f('ix_ipos_total_subscription'), 'ipos', ['total_subscription'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('gmp_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('gmp_amount', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmp_history_id'), 'gmp_history', ['id'], unique=False)
    op.create_index(op.f('ix_gmp_history_ipo_id'), 'gmp_history', ['ipo_id'], unique=False)
    op.create_index(op.f('ix_gmp_history_recorded_at'), 'gmp_history', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmp_history_recorded_at'), table_name='gmp_history')
    op.drop_index(op.f('ix_gmp_history_ipo_id'), table_name='gmp_history')
    op.drop_index(op.f('ix_gmp_history_id'), table_name='gmp_history')
    op.drop_table('gmp_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ipos_total_subscription'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_symbol'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_status'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_risk_score'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_open_date'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_ml_processed'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_listing_date'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_industry_sector'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_id'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_company_name'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_close_date'), table_name='ipos')
    op.drop_table('ipos')
    # ### end Alembic commands ###
